@startuml

class Figure {
    + Color
    + StepCount
    - is_pass_diagonal(Square start, Square end)
    - is_pass_line(Square start, Square end)
    - is_valid_turn(MovementContext context)
    + ConfirmMove()
    + isValideMove(MovementContext context)
    + isValideAttack(MovementContext context)
}

Interface I_Status{
    + bool is_empty(Square)
    + get_figure(Square)
    + isCheck(Color)
    + isMat()
    + turnColor()
}
Interface I_GameBoard{
    + getBoard() -> list
    + MakeMove(to_square: str) -> (bool,str)
    + newGame()
    + getTurn() -> str
    + getStatus() -> str
    + SelectFigure(square:str) -> (bool, str)
    + isSelected() -> bool
    + getSelectedIndexes() -> (int,int)
}

class GameBoard extends I_GameBoard, I_Status {
    - board_storage
    - create_Context(board: BoardStorage)-> I_MovementContext
    + Move(Square start, Square end)

}

class BoardSorage {
    + get_clone()
    + get_figure(Square)
    + set_figure(Square)
    + get_line(Square start, Square end)
    + get_diag(Square start, Square end)
    + get_occupied_coordinates(Color)
    + get_king_square(Color)
}

GameBoard *- BoardSorage
Game *- GameBoard

class Game{
    - player1: Player
    - player2: Player
    - game_board: GameBoard
    + add_Palyer(player: Player)
    + start_game()
    + make_move(player, list(start, end))
}

class Player{
    - Color
}

class Square{
    - char Coll
    - int Row
    +RowIndex()
    +ColIndex()
}



Interface I_MovementContext{
 
    + current_position() -> Square
    + new_position() -> Square
    + turnColor() -> Color
    + isSquareEmpty(Square) -> bool
    + isPassEmpty() -> bool
    + isNewPositionPartnerOccupied() -> bool
    + getFiguresOnPassAmmount() -> int
    + getFigure(Square) -> Figure
    + getPrevTurnFigure() -> Figure
    + setEnPassantPawn(Square)
    
    
}

@enduml