from abc import ABC, abstractmethod
from typing import Protocol
from Core.Square import Square
from Core.Color import Color

class I_Figure(ABC): ...


class I_MovementContext(ABC):
    @abstractmethod
    def current_position(self) -> Square: ... 
    @abstractmethod
    def new_position(self) -> Square: ...
    @abstractmethod
    def turnColor(self)-> Color : ...
    @abstractmethod
    def isSquareEmpty(self, square: Square)-> bool : ...
    @abstractmethod
    def isPassEmpty(self) -> bool : ...
    @abstractmethod
    def isNewPositionPartnerOccupied(self) -> bool : ...
    @abstractmethod
    def getFiguresOnPassAmmount(self) -> int: ...
    @abstractmethod
    def getFigure(self, square: Square) -> I_Figure: ...
    @abstractmethod
    def getPrevTurnFigure(self)-> I_Figure: ...
    @abstractmethod
    def setEnPassantPawn(self,square : Square):...

class I_GameBoard(Protocol):
    def getBoard(self) -> list: ...
    def MakeMove(self,to_square: str) -> (bool,str): ...
    def newGame(self):...
    def getTurn(self) -> str:...
    def getStatus(self) -> str:...
    def SelectFigure(self,square: str) -> (bool, str):...
    def isSelected(self) -> bool:... 
    def getSelectedIndexes(self) -> (int,int):...

class I_Status(Protocol):
    def isCheck(self,color: Color) -> bool:...
    def isMat(self) -> bool:...