from abc import ABC, abstractmethod
from Context import Figure
from Context.Square import Square
from Context.Color import Color

class I_MovementContext(ABC):
    @abstractmethod
    def current_position(self) -> Square: ... 
    @abstractmethod
    def new_position(self) -> Square: ...
    @abstractmethod
    def turnColor(self)-> Color : ...
    @abstractmethod
    def isSquareEmpty(self, square: Square)-> bool : ...
    @abstractmethod
    def isPassEmpty(self) -> bool : ...
    @abstractmethod
    def isNewPositionPartnerOccupied(self) -> bool : ...
    @abstractmethod
    def getFiguresOnPassAmmount(self) -> int: ...
    @abstractmethod
    def getFigure(self, square: Square) -> Figure: ...
    @abstractmethod
    def getPrevTurnFigure(self)-> Figure: ...
    @abstractmethod
    def setEnPassantPawn(self,square : Square):...

